#FROM zikalino/autorest.cli.base
#FROM ${DOCKERSERVER}/autorest.cli.base
FROM terraformbuild.azurecr.io/autorest.cli.base

MAINTAINER zikalino

#ADD . /autorest.cli
# RUN cd /autorest.cli; npm install
ADD autorest.cli /autorest.cli
RUN cd /autorest.cli; npm install; tsc -p tsconfig.json
ADD cli-input-tools /cli-input-tools
ADD magic-modules /magic-modules
RUN bash -l -c 'cd /magic-modules;gem install bundler:2.0.1; bundle update --bundler; bundle install'
ADD terraform/run-incremental.sh /run-incremental.sh
RUN chmod +x /run-incremental.sh
ENTRYPOINT ["bash", "/run-incremental.sh"]
