FROM ubuntu:xenial
MAINTAINER zikalino

RUN apt-get update
RUN apt-get install -y git curl gnupg ruby

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN npm -g install autorest

RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-get update
RUN apt-get install -y apt-transport-https libcurl3 libicu55
RUN apt-get install -y dotnet-runtime-2.0.5
RUN apt-get install -y dotnet-sdk-2.1.4
ADD autorest.cli /autorest.cli
ADD magic-modules /magic-modules
ADD run.sh /run.sh
RUN cd /autorest.cli; npm install

#install ruby 2.6.0
RUN apt update
RUN apt install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(rbenv init -)"' >> ~/.bashrc
RUN source ~/.bashrc
RUN type rbenv
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
RUN rbenv install -l
RUN rbenv install 2.6.0
RUN rbenv global 2.6.0
RUN ruby -v


#RUN apt-get install -y software-properties-common build-essential
#RUN gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
#RUN curl -L https://get.rvm.io | bash -s stable --ruby
#RUN /bin/bash -c "source /usr/local/rvm/scripts/rvm; rvm install 2.6.0; rvm use 2.6.0; rvm rubygems latest;"
#RUN apt-get update
#RUN /bin/bash -l -c "gem install bundler"
