// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm



func resourceArmBackend() *schema.Resource {
    return &schema.Resource{
        Create: resourceArmBackendCreate,
        Read: resourceArmBackendRead,
        Update: resourceArmBackendUpdate,
        Delete: resourceArmBackendDelete,

        Importer: &schema.ResourceImporter{
            State: schema.ImportStatePassthrough,
        },


        Schema: map[string]*schema.Schema{
            "resource_group": azure.SchemaResourceGroupNameDiffSuppress(),

            "backendid": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "host": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "service_name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "skip_certificate_chain_validation": {
                Type: schema.TypeBool,
                Optional: true,
                ForceNew: true,
            },
        },
    }
}

func resourceArmBackendCreate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).backendsClient
    ctx := meta.(*ArmClient).StopContext

    resourceGroup := d.Get("resource_group").(string)
    backendid := d.Get("backendid").(string)
    serviceName := d.Get("service_name").(string)

    if features.ShouldResourcesBeImported() && d.IsNewResource() {
        existing, err := client.Get(ctx, resourceGroup, serviceName, backendid)
        if err != nil {
            if !utils.ResponseWasNotFound(existing.Response) {
                return fmt.Errorf("Error checking for present of existing Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
            }
        }
        if existing.ID != nil && *existing.ID != "" {
            return tf.ImportAsExistsError("azurerm_backend", *existing.ID)
        }
    }

    host := d.Get("host").(string)
    skipCertificateChainValidation := d.Get("skip_certificate_chain_validation").(bool)

    parameters := apimanagement.BackendContract{
        Host: utils.String(host),
        SkipCertificateChainValidation: utils.Bool(skipCertificateChainValidation),
    }


    if _, err := client.CreateOrUpdate(ctx, resourceGroup, serviceName, backendid, parameters); err != nil {
        return fmt.Errorf("Error creating Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
    }


    resp, err := client.Get(ctx, resourceGroup, serviceName, backendid)
    if err != nil {
        return fmt.Errorf("Error retrieving Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
    }
    if resp.ID == nil {
        return fmt.Errorf("Cannot read Backend (Backendid %q / Service Name %q / Resource Group %q) ID", backendid, serviceName, resourceGroup)
    }
    d.SetId(*resp.ID)

    return resourceArmBackendRead(d, meta)
}

func resourceArmBackendRead(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).backendsClient
    ctx := meta.(*ArmClient).StopContext

    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    serviceName := id.Path["service"]
    backendid := id.Path["backends"]

    resp, err := client.Get(ctx, resourceGroup, serviceName, backendid)
    if err != nil {
        if utils.ResponseWasNotFound(resp.Response) {
            log.Printf("[INFO] Backend %q does not exist - removing from state", d.Id())
            d.SetId("")
            return nil
        }
        return fmt.Errorf("Error reading Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
    }


    d.Set("resource_group", resourceGroup)
    d.Set("backendid", backendid)
    d.Set("host", resp.Host)
    d.Set("service_name", serviceName)
    d.Set("skip_certificate_chain_validation", resp.SkipCertificateChainValidation)

    return nil
}

func resourceArmBackendUpdate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).backendsClient
    ctx := meta.(*ArmClient).StopContext

    resourceGroup := d.Get("resource_group").(string)
    backendid := d.Get("backendid").(string)
    host := d.Get("host").(string)
    serviceName := d.Get("service_name").(string)
    skipCertificateChainValidation := d.Get("skip_certificate_chain_validation").(bool)

    parameters := apimanagement.BackendContract{
        Host: utils.String(host),
        SkipCertificateChainValidation: utils.Bool(skipCertificateChainValidation),
    }


    if _, err := client.Update(ctx, resourceGroup, serviceName, backendid, parameters); err != nil {
        return fmt.Errorf("Error updating Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
    }

    return resourceArmBackendRead(d, meta)
}

func resourceArmBackendDelete(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).backendsClient
    ctx := meta.(*ArmClient).StopContext


    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    serviceName := id.Path["service"]
    backendid := id.Path["backends"]

    if _, err := client.Delete(ctx, resourceGroup, serviceName, backendid); err != nil {
        return fmt.Errorf("Error deleting Backend (Backendid %q / Service Name %q / Resource Group %q): %+v", backendid, serviceName, resourceGroup, err)
    }

    return nil
}
