// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm



func resourceArmLocalNetworkGateway() *schema.Resource {
    return &schema.Resource{
        Create: resourceArmLocalNetworkGatewayCreateUpdate,
        Read: resourceArmLocalNetworkGatewayRead,
        Update: resourceArmLocalNetworkGatewayCreateUpdate,
        Delete: resourceArmLocalNetworkGatewayDelete,

        Importer: &schema.ResourceImporter{
            State: schema.ImportStatePassthrough,
        },


        Schema: map[string]*schema.Schema{
            "name": {
                Type: schema.TypeString,
                Computed: true,
            },

            "location": azure.SchemaLocation(),

            "resource_group": azure.SchemaResourceGroupNameDiffSuppress(),

            "local_network_address_space": {
                Type: schema.TypeList,
                Required: true,
                MaxItems: 1,
                Elem: &schema.Resource{
                    Schema: map[string]*schema.Schema{
                        "address_prefixes": {
                            Type: schema.TypeList,
                            Optional: true,
                            Elem: &schema.Schema{
                                Type: schema.TypeString,
                            },
                        },
                    },
                },
            },

            "local_network_gateway_name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "bgp_settings": {
                Type: schema.TypeList,
                Optional: true,
                MaxItems: 1,
                Elem: &schema.Resource{
                    Schema: map[string]*schema.Schema{
                        "asn": {
                            Type: schema.TypeInt,
                            Optional: true,
                        },
                        "bgp_peering_address": {
                            Type: schema.TypeString,
                            Optional: true,
                        },
                        "peer_weight": {
                            Type: schema.TypeInt,
                            Optional: true,
                        },
                    },
                },
            },

            "etag": {
                Type: schema.TypeString,
                Optional: true,
                ForceNew: true,
            },

            "gateway_ip_address": {
                Type: schema.TypeString,
                Optional: true,
            },

            "resource_guid": {
                Type: schema.TypeString,
                Optional: true,
            },

            "provisioning_state": {
                Type: schema.TypeString,
                Computed: true,
            },

            "type": {
                Type: schema.TypeString,
                Computed: true,
            },

            "tags": tags.Schema(),
        },
    }
}

func resourceArmLocalNetworkGatewayCreateUpdate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).localNetworkGatewaysClient
    ctx := meta.(*ArmClient).StopContext

    resourceGroup := d.Get("resource_group").(string)
    localNetworkGatewayName := d.Get("local_network_gateway_name").(string)

    if features.ShouldResourcesBeImported() && d.IsNewResource() {
        existing, err := client.Get(ctx, resourceGroup, localNetworkGatewayName)
        if err != nil {
            if !utils.ResponseWasNotFound(existing.Response) {
                return fmt.Errorf("Error checking for present of existing Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
            }
        }
        if existing.ID != nil && *existing.ID != "" {
            return tf.ImportAsExistsError("azurerm_local_network_gateway", *existing.ID)
        }
    }

    id := d.Get("id").(string)
    location := azure.NormalizeLocation(d.Get("location").(string))
    bgpSettings := d.Get("bgp_settings").([]interface{})
    etag := d.Get("etag").(string)
    gatewayIpAddress := d.Get("gateway_ip_address").(string)
    localNetworkAddressSpace := d.Get("local_network_address_space").([]interface{})
    resourceGuid := d.Get("resource_guid").(string)
    t := d.Get("tags").(map[string]interface{})

    parameters := network.LocalNetworkGateway{
        Etag: utils.String(etag),
        ID: utils.String(id),
        Location: utils.String(location),
        LocalNetworkGatewayPropertiesFormat: &network.LocalNetworkGatewayPropertiesFormat{
            BgpSettings: expandArmLocalNetworkGatewayBgpSettings(bgpSettings),
            GatewayIpAddress: utils.String(gatewayIpAddress),
            LocalNetworkAddressSpace: expandArmLocalNetworkGatewayAddressSpace(localNetworkAddressSpace),
            ResourceGuid: utils.String(resourceGuid),
        },
        Tags: tags.Expand(t),
    }


    future, err := client.CreateOrUpdate(ctx, resourceGroup, localNetworkGatewayName, parameters)
    if err != nil {
        return fmt.Errorf("Error creating Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
    }
    if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
        return fmt.Errorf("Error waiting for creation of Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
    }


    resp, err := client.Get(ctx, resourceGroup, localNetworkGatewayName)
    if err != nil {
        return fmt.Errorf("Error retrieving Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
    }
    if resp.ID == nil {
        return fmt.Errorf("Cannot read Local Network Gateway (Local Network Gateway Name %q / Resource Group %q) ID", localNetworkGatewayName, resourceGroup)
    }
    d.SetId(*resp.ID)

    return resourceArmLocalNetworkGatewayRead(d, meta)
}

func resourceArmLocalNetworkGatewayRead(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).localNetworkGatewaysClient
    ctx := meta.(*ArmClient).StopContext

    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    localNetworkGatewayName := id.Path["localNetworkGateways"]

    resp, err := client.Get(ctx, resourceGroup, localNetworkGatewayName)
    if err != nil {
        if utils.ResponseWasNotFound(resp.Response) {
            log.Printf("[INFO] Local Network Gateway %q does not exist - removing from state", d.Id())
            d.SetId("")
            return nil
        }
        return fmt.Errorf("Error reading Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
    }


    d.Set("name", resp.Name)
    d.Set("resource_group", resourceGroup)
    if location := resp.Location; location != nil {
        d.Set("location", azure.NormalizeLocation(*location))
    }
    if localNetworkGatewayPropertiesFormat := resp.LocalNetworkGatewayPropertiesFormat; localNetworkGatewayPropertiesFormat != nil {
        if err := d.Set("bgp_settings", flattenArmLocalNetworkGatewayBgpSettings(localNetworkGatewayPropertiesFormat.BgpSettings)); err != nil {
            return fmt.Errorf("Error setting `bgp_settings`: %+v", err)
        }
        d.Set("gateway_ip_address", localNetworkGatewayPropertiesFormat.GatewayIpAddress)
        if err := d.Set("local_network_address_space", flattenArmLocalNetworkGatewayAddressSpace(localNetworkGatewayPropertiesFormat.LocalNetworkAddressSpace)); err != nil {
            return fmt.Errorf("Error setting `local_network_address_space`: %+v", err)
        }
        d.Set("provisioning_state", localNetworkGatewayPropertiesFormat.ProvisioningState)
        d.Set("resource_guid", localNetworkGatewayPropertiesFormat.ResourceGuid)
    }
    d.Set("etag", resp.Etag)
    d.Set("local_network_gateway_name", localNetworkGatewayName)
    d.Set("type", resp.Type)

    return tags.FlattenAndSet(d, resp.Tags)
}


func resourceArmLocalNetworkGatewayDelete(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).localNetworkGatewaysClient
    ctx := meta.(*ArmClient).StopContext


    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    localNetworkGatewayName := id.Path["localNetworkGateways"]

    future, err := client.Delete(ctx, resourceGroup, localNetworkGatewayName)
    if err != nil {
        if response.WasNotFound(future.Response()) {
            return nil
        }
        return fmt.Errorf("Error deleting Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
    }

    if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
        if !response.WasNotFound(future.Response()) {
            return fmt.Errorf("Error waiting for deleting Local Network Gateway (Local Network Gateway Name %q / Resource Group %q): %+v", localNetworkGatewayName, resourceGroup, err)
        }
    }

    return nil
}

func expandArmLocalNetworkGatewayBgpSettings(input []interface{}) *network.BgpSettings {
    if len(input) == 0 {
        return nil
    }
    v := input[0].(map[string]interface{})

    asn := v["asn"].(int)
    bgpPeeringAddress := v["bgp_peering_address"].(string)
    peerWeight := v["peer_weight"].(int)

    result := network.BgpSettings{
        Asn: utils.Int64(int64(asn)),
        BgpPeeringAddress: utils.String(bgpPeeringAddress),
        PeerWeight: utils.Int32(int32(peerWeight)),
    }
    return &result
}

func expandArmLocalNetworkGatewayAddressSpace(input []interface{}) *network.AddressSpace {
    if len(input) == 0 {
        return nil
    }
    v := input[0].(map[string]interface{})

    addressPrefixes := v["address_prefixes"].([]interface{})

    result := network.AddressSpace{
        AddressPrefixes: utils.ExpandStringSlice(addressPrefixes),
    }
    return &result
}


func flattenArmLocalNetworkGatewayBgpSettings(input *network.BgpSettings) []interface{} {
    if input == nil {
        return make([]interface{}, 0)
    }

    result := make(map[string]interface{})

    if asn := input.Asn; asn != nil {
        result["asn"] = int(*asn)
    }
    if bgpPeeringAddress := input.BgpPeeringAddress; bgpPeeringAddress != nil {
        result["bgp_peering_address"] = *bgpPeeringAddress
    }
    if peerWeight := input.PeerWeight; peerWeight != nil {
        result["peer_weight"] = int(*peerWeight)
    }

    return []interface{}{result}
}

func flattenArmLocalNetworkGatewayAddressSpace(input *network.AddressSpace) []interface{} {
    if input == nil {
        return make([]interface{}, 0)
    }

    result := make(map[string]interface{})

    result["address_prefixes"] = utils.FlattenStringSlice(input.AddressPrefixes)

    return []interface{}{result}
}
