// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm



func resourceArmRole() *schema.Resource {
    return &schema.Resource{
        Create: resourceArmRoleCreateUpdate,
        Read: resourceArmRoleRead,
        Update: resourceArmRoleCreateUpdate,
        Delete: resourceArmRoleDelete,

        Importer: &schema.ResourceImporter{
            State: schema.ImportStatePassthrough,
        },


        Schema: map[string]*schema.Schema{
            "name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "resource_group": azure.SchemaResourceGroupNameDiffSuppress(),

            "device_name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
                ValidateFunc: validate.NoEmptyStrings,
            },

            "type": {
                Type: schema.TypeString,
                Computed: true,
            },
        },
    }
}

func resourceArmRoleCreateUpdate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).rolesClient
    ctx := meta.(*ArmClient).StopContext

    name := d.Get("name").(string)
    resourceGroup := d.Get("resource_group").(string)
    deviceName := d.Get("device_name").(string)

    if features.ShouldResourcesBeImported() && d.IsNewResource() {
        existing, err := client.Get(ctx, deviceName, name, resourceGroup)
        if err != nil {
            if !utils.ResponseWasNotFound(existing.Response) {
                return fmt.Errorf("Error checking for present of existing Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
            }
        }
        if existing.ID != nil && *existing.ID != "" {
            return tf.ImportAsExistsError("azurerm_role", *existing.ID)
        }
    }


    role := databoxedge.Role{
    }


    future, err := client.CreateOrUpdate(ctx, deviceName, name, resourceGroup, role)
    if err != nil {
        return fmt.Errorf("Error creating Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
    }
    if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
        return fmt.Errorf("Error waiting for creation of Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
    }


    resp, err := client.Get(ctx, deviceName, name, resourceGroup)
    if err != nil {
        return fmt.Errorf("Error retrieving Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
    }
    if resp.ID == nil {
        return fmt.Errorf("Cannot read Role %q (Resource Group %q / Device Name %q) ID", name, resourceGroup, deviceName)
    }
    d.SetId(*resp.ID)

    return resourceArmRoleRead(d, meta)
}

func resourceArmRoleRead(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).rolesClient
    ctx := meta.(*ArmClient).StopContext

    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    deviceName := id.Path["dataBoxEdgeDevices"]
    name := id.Path["roles"]
    resourceGroup := id.ResourceGroup

    resp, err := client.Get(ctx, deviceName, name, resourceGroup)
    if err != nil {
        if utils.ResponseWasNotFound(resp.Response) {
            log.Printf("[INFO] Role %q does not exist - removing from state", d.Id())
            d.SetId("")
            return nil
        }
        return fmt.Errorf("Error reading Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
    }


    d.Set("name", name)
    d.Set("resource_group", resourceGroup)
    d.Set("device_name", deviceName)
    d.Set("type", resp.Type)

    return nil
}


func resourceArmRoleDelete(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).rolesClient
    ctx := meta.(*ArmClient).StopContext


    id, err := azure.ParseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    deviceName := id.Path["dataBoxEdgeDevices"]
    name := id.Path["roles"]
    resourceGroup := id.ResourceGroup

    future, err := client.Delete(ctx, deviceName, name, resourceGroup)
    if err != nil {
        if response.WasNotFound(future.Response()) {
            return nil
        }
        return fmt.Errorf("Error deleting Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
    }

    if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
        if !response.WasNotFound(future.Response()) {
            return fmt.Errorf("Error waiting for deleting Role %q (Resource Group %q / Device Name %q): %+v", name, resourceGroup, deviceName, err)
        }
    }

    return nil
}
