// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
    "fmt"
    "strings"
    "testing"

    "github.com/hashicorp/terraform/helper/acctest"
    "github.com/hashicorp/terraform/helper/resource"
    "github.com/hashicorp/terraform/terraform"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)


func testCheckAzureRMMediaGraphExists(resourceName string) resource.TestCheckFunc {
    return func(s *terraform.State) error {
        rs, ok := s.RootModule().Resources[resourceName]
        if !ok {
            return fmt.Errorf("Media Graph not found: %s", resourceName)
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        accountName := rs.Primary.Attributes["account_name"]
        mediaGraphName := rs.Primary.Attributes["media_graph_name"]

        client := testAccProvider.Meta().(*ArmClient).mediaGraphsClient
        ctx := testAccProvider.Meta().(*ArmClient).StopContext

        if resp, err := client.Get(ctx, resourceGroup, accountName, mediaGraphName); err != nil {
            if utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Media Graph (Media Graph Name %q / Account Name %q / Resource Group %q) does not exist", mediaGraphName, accountName, resourceGroup)
            }
            return fmt.Errorf("Bad: Get on mediaGraphsClient: %+v", err)
        }

        return nil
    }
}

func testCheckAzureRMMediaGraphDestroy(s *terraform.State) error {
    client := testAccProvider.Meta().(*ArmClient).mediaGraphsClient
    ctx := testAccProvider.Meta().(*ArmClient).StopContext

    for _, rs := range s.RootModule().Resources {
        if rs.Type != "azurerm_media_graph" {
            continue
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        accountName := rs.Primary.Attributes["account_name"]
        mediaGraphName := rs.Primary.Attributes["media_graph_name"]

        if resp, err := client.Get(ctx, resourceGroup, accountName, mediaGraphName); err != nil {
            if !utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Get on mediaGraphsClient: %+v", err)
            }
        }

        return nil
    }

    return nil
}
