// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
    "fmt"
    "strings"
    "testing"

    "github.com/hashicorp/terraform/helper/acctest"
    "github.com/hashicorp/terraform/helper/resource"
    "github.com/hashicorp/terraform/terraform"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)


func testCheckAzureRMReplicationMigrationItemExists(resourceName string) resource.TestCheckFunc {
    return func(s *terraform.State) error {
        rs, ok := s.RootModule().Resources[resourceName]
        if !ok {
            return fmt.Errorf("Replication Migration Item not found: %s", resourceName)
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        fabricName := rs.Primary.Attributes["fabric_name"]
        migrationItemName := rs.Primary.Attributes["migration_item_name"]
        protectionContainerName := rs.Primary.Attributes["protection_container_name"]
        resourceName := rs.Primary.Attributes["resource_name"]

        client := testAccProvider.Meta().(*ArmClient).replicationMigrationItemsClient
        ctx := testAccProvider.Meta().(*ArmClient).StopContext

        if resp, err := client.Get(ctx, resourceName, resourceGroup, fabricName, protectionContainerName, migrationItemName); err != nil {
            if utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Replication Migration Item (Migration Item Name %q / Protection Container Name %q / Fabric Name %q / Resource Group %q / Resource Name %q) does not exist", migrationItemName, protectionContainerName, fabricName, resourceGroup, resourceName)
            }
            return fmt.Errorf("Bad: Get on replicationMigrationItemsClient: %+v", err)
        }

        return nil
    }
}

func testCheckAzureRMReplicationMigrationItemDestroy(s *terraform.State) error {
    client := testAccProvider.Meta().(*ArmClient).replicationMigrationItemsClient
    ctx := testAccProvider.Meta().(*ArmClient).StopContext

    for _, rs := range s.RootModule().Resources {
        if rs.Type != "azurerm_replication_migration_item" {
            continue
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        fabricName := rs.Primary.Attributes["fabric_name"]
        migrationItemName := rs.Primary.Attributes["migration_item_name"]
        protectionContainerName := rs.Primary.Attributes["protection_container_name"]
        resourceName := rs.Primary.Attributes["resource_name"]

        if resp, err := client.Get(ctx, resourceName, resourceGroup, fabricName, protectionContainerName, migrationItemName); err != nil {
            if !utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Get on replicationMigrationItemsClient: %+v", err)
            }
        }

        return nil
    }

    return nil
}
