// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
    "fmt"
    "strings"
    "testing"

    "github.com/hashicorp/terraform/helper/acctest"
    "github.com/hashicorp/terraform/helper/resource"
    "github.com/hashicorp/terraform/terraform"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)


func testCheckAzureRMCustomDomainExists(resourceName string) resource.TestCheckFunc {
    return func(s *terraform.State) error {
        rs, ok := s.RootModule().Resources[resourceName]
        if !ok {
            return fmt.Errorf("Custom Domain not found: %s", resourceName)
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        customDomainName := rs.Primary.Attributes["custom_domain_name"]
        endpointName := rs.Primary.Attributes["endpoint_name"]
        profileName := rs.Primary.Attributes["profile_name"]

        client := testAccProvider.Meta().(*ArmClient).customDomainsClient
        ctx := testAccProvider.Meta().(*ArmClient).StopContext

        if resp, err := client.Get(ctx, resourceGroup, profileName, endpointName, customDomainName); err != nil {
            if utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Custom Domain (Custom Domain Name %q / Endpoint Name %q / Profile Name %q / Resource Group %q) does not exist", customDomainName, endpointName, profileName, resourceGroup)
            }
            return fmt.Errorf("Bad: Get on customDomainsClient: %+v", err)
        }

        return nil
    }
}

func testCheckAzureRMCustomDomainDestroy(s *terraform.State) error {
    client := testAccProvider.Meta().(*ArmClient).customDomainsClient
    ctx := testAccProvider.Meta().(*ArmClient).StopContext

    for _, rs := range s.RootModule().Resources {
        if rs.Type != "azurerm_custom_domain" {
            continue
        }

        resourceGroup := rs.Primary.Attributes["resource_group"]
        customDomainName := rs.Primary.Attributes["custom_domain_name"]
        endpointName := rs.Primary.Attributes["endpoint_name"]
        profileName := rs.Primary.Attributes["profile_name"]

        if resp, err := client.Get(ctx, resourceGroup, profileName, endpointName, customDomainName); err != nil {
            if !utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Get on customDomainsClient: %+v", err)
            }
        }

        return nil
    }

    return nil
}
